In [47]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

pt = PowerTransformer()
data = [[1, 2], [3, 2], [4, 5]]
print(pt.fit(data))
PowerTransformer()
print(pt.lambdas_)

X=pt.transform(data)
ef

PowerTransformer()
[ 1.38668178 -3.10053332]


array([[-1.31616039, -0.70710678],
       [ 0.20998268, -0.70710678],
       [ 1.1061777 ,  1.41421356]])

In [25]:
pt.inverse_transform(X)

array([[1., 2.],
       [3., 2.],
       [4., 5.]])

In [31]:
from scipy.stats import yeojohnson

x=np.linspace(-2,2,100)
for l in [-1,0.5,0.3,0,2,3]:
  y=yeojohnson(x,l)
y

array([-0.66666667, -0.66211604, -0.65743945, -0.65263158, -0.64768683,
       -0.64259928, -0.63736264, -0.63197026, -0.62641509, -0.62068966,
       -0.61478599, -0.60869565, -0.60240964, -0.59591837, -0.58921162,
       -0.58227848, -0.5751073 , -0.56768559, -0.56      , -0.5520362 ,
       -0.5437788 , -0.53521127, -0.52631579, -0.51707317, -0.50746269,
       -0.49746193, -0.48704663, -0.47619048, -0.46486486, -0.45303867,
       -0.44067797, -0.42774566, -0.41420118, -0.4       , -0.38509317,
       -0.36942675, -0.35294118, -0.33557047, -0.31724138, -0.29787234,
       -0.27737226, -0.2556391 , -0.23255814, -0.208     , -0.18181818,
       -0.15384615, -0.12389381, -0.09174312, -0.05714286, -0.01980198,
        0.02061289,  0.06435336,  0.11155668,  0.16235477,  0.21687954,
        0.27526292,  0.33763682,  0.40413316,  0.47488386,  0.55002084,
        0.62967601,  0.71398129,  0.80306861,  0.89706987,  0.996117  ,
        1.10034192,  1.20987654,  1.32485279,  1.44540257,  1.57

In [71]:
pt = PowerTransformer()
data = np.linspace(-2,2,100)
a=data.reshape(-1,1)
pt.fit(a)
X=pt.transform(a)
X

array([[-1.71481603],
       [-1.68017329],
       [-1.64553054],
       [-1.61088779],
       [-1.57624504],
       [-1.5416023 ],
       [-1.50695955],
       [-1.4723168 ],
       [-1.43767405],
       [-1.4030313 ],
       [-1.36838856],
       [-1.33374581],
       [-1.29910306],
       [-1.26446031],
       [-1.22981756],
       [-1.19517482],
       [-1.16053207],
       [-1.12588932],
       [-1.09124657],
       [-1.05660382],
       [-1.02196108],
       [-0.98731833],
       [-0.95267558],
       [-0.91803283],
       [-0.88339008],
       [-0.84874734],
       [-0.81410459],
       [-0.77946184],
       [-0.74481909],
       [-0.71017634],
       [-0.67553359],
       [-0.64089085],
       [-0.6062481 ],
       [-0.57160535],
       [-0.5369626 ],
       [-0.50231985],
       [-0.46767711],
       [-0.43303436],
       [-0.39839161],
       [-0.36374886],
       [-0.32910611],
       [-0.29446336],
       [-0.25982062],
       [-0.22517787],
       [-0.19053512],
       [-0

In [74]:
b=pt.inverse_transform(a)
b.reshape(1,-1)

array([[-2.33261173, -2.28548826, -2.23836479, -2.19124132, -2.14411785,
        -2.09699439, -2.04987092, -2.00274745, -1.95562398, -1.90850051,
        -1.86137704, -1.81425357, -1.7671301 , -1.72000663, -1.67288316,
        -1.62575969, -1.57863622, -1.53151275, -1.48438928, -1.43726581,
        -1.39014234, -1.34301887, -1.2958954 , -1.24877193, -1.20164846,
        -1.15452499, -1.10740152, -1.06027805, -1.01315458, -0.96603112,
        -0.91890765, -0.87178418, -0.82466071, -0.77753724, -0.73041377,
        -0.6832903 , -0.63616683, -0.58904336, -0.54191989, -0.49479642,
        -0.44767295, -0.40054948, -0.35342601, -0.30630254, -0.25917908,
        -0.21205561, -0.16493214, -0.11780867, -0.0706852 , -0.02356173,
         0.02356174,  0.07068521,  0.11780868,  0.16493215,  0.21205562,
         0.25917908,  0.30630255,  0.35342602,  0.40054949,  0.44767296,
         0.49479643,  0.5419199 ,  0.58904337,  0.63616684,  0.68329031,
         0.73041377,  0.77753724,  0.82466071,  0.8